/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-12 03:27:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class emp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fn_list(){\r\n");
      out.write("	var param = \"\";\r\n");
      out.write("	param += \"dummy=\" + Math.random();\r\n");
      out.write("	param += \"&a=777\";\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"ajaxlist\",\r\n");
      out.write("		data : param,\r\n");
      out.write("		dataType : \"json\",\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		async: false,\r\n");
      out.write("		success : function(res) {\r\n");
      out.write("			var list = res;\r\n");
      out.write("			\r\n");
      out.write("			var html = ``;\r\n");
      out.write("			\r\n");
      out.write("			for(var i=0;i<list.length;i++){\r\n");
      out.write("				var e_id = list[i].e_id;\r\n");
      out.write("				var e_name = list[i].e_name;\r\n");
      out.write("				var sex = list[i].sex;\r\n");
      out.write("				var addr = list[i].addr;\r\n");
      out.write("				html += `\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><a href=\"javascript:fn_one('`+e_id+`')\">`+e_id+`</a></td>\r\n");
      out.write("					<td>`+e_name+`</td>\r\n");
      out.write("					<td>`+sex+`</td>\r\n");
      out.write("					<td>`+addr+`</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				`;\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#mytbody\").html(html);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_one(e_id){\r\n");
      out.write("	var param = \"\";\r\n");
      out.write("	param += \"dummy=\" + Math.random();\r\n");
      out.write("	param += \"&e_id=\"+e_id;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"ajaxone\",\r\n");
      out.write("		data : param,\r\n");
      out.write("		dataType : \"json\",\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		async: false,\r\n");
      out.write("		success : function(res) {\r\n");
      out.write("			var emp = res;\r\n");
      out.write("			$(\"#e_id\").val(emp.e_id);\r\n");
      out.write("			$(\"#e_name\").val(emp.e_name);\r\n");
      out.write("			$(\"#sex\").val(emp.sex);\r\n");
      out.write("			$(\"#addr\").val(emp.addr);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_add(){\r\n");
      out.write("	var param = \"\";\r\n");
      out.write("	param += \"dummy=\" + Math.random();\r\n");
      out.write("	param += \"&e_name=\"+$(\"#e_name\").val();\r\n");
      out.write("	param += \"&sex=\"+$(\"#sex\").val();\r\n");
      out.write("	param += \"&addr=\"+$(\"#addr\").val();\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"ajaxadd\",\r\n");
      out.write("		data : param,\r\n");
      out.write("		dataType : \"json\",\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		async: false,\r\n");
      out.write("		success : function(res) {\r\n");
      out.write("			var cnt = res.cnt;\r\n");
      out.write("			if(cnt ==1){\r\n");
      out.write("				alert(\"정상적으로 추가하였습니다.\");\r\n");
      out.write("				fn_list();\r\n");
      out.write("				$(\"#e_id\").val(\"\");\r\n");
      out.write("				$(\"#e_name\").val(\"\");\r\n");
      out.write("				$(\"#sex\").val(\"\");\r\n");
      out.write("				$(\"#addr\").val(\"\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"fn_list()\">\r\n");
      out.write("<table border=\"1px\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>사번</td>\r\n");
      out.write("			<td>이름</td>\r\n");
      out.write("			<td>성별</td>\r\n");
      out.write("			<td>주소</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody id=\"mytbody\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>1</td>\r\n");
      out.write("			<td>1</td>\r\n");
      out.write("			<td>1</td>\r\n");
      out.write("			<td>1</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1px\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>사번</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"e_id\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>이름</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"e_name\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>성별</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"sex\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>주소</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"addr\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"2\">\r\n");
      out.write("			<input type=\"button\" value=\"추가\" onclick=\"fn_add()\" />\r\n");
      out.write("			<input type=\"button\" value=\"수정\" />\r\n");
      out.write("			<input type=\"button\" value=\"삭제\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
